### ISSUE TITLE
Incorrect result for identity matrix

### ISSUE THREAD

**Issue by Sanqui** [staltz/matrixmultiplication.xyz#9]
The result of multiplying two identity matrixes should obviously be the identity matrix.  matrixmultiplication.xyz incorrectly gives a matrix of threes (or presumably ns).

Screenshots:

![2017-06-05t17 39 57-selection](https://cloud.githubusercontent.com/assets/289437/26791040/2d7196ae-4a16-11e7-961e-fab60628a391.png)
![2017-06-05t17 40 16-selection](https://cloud.githubusercontent.com/assets/289437/26791043/2fb1963a-4a16-11e7-9876-e45738cf4c38.png)
![2017-06-05t17 40 24-selection](https://cloud.githubusercontent.com/assets/289437/26791044/3147a444-4a16-11e7-85d2-fd71a7d04c9e.png)

This is happening on Firefox.

**Comment by Sentri** [comment]
As far as I can tell, it seems to treat all zeroes as ones.
![image](https://cloud.githubusercontent.com/assets/753072/26795267/be6d1680-4a2d-11e7-9531-0e55a430d1fc.png)

**Comment by staltz** [comment]
Fixed. Thanks @Sanqui  and @Sentri
